### ISSUE TITLE
Large album covers not read

### ISSUE THREAD

**Issue by e-gor** [JamesHeinrich/getID3#100]
When an mp3 file with id3v2 (3 or 4) has an album cover in the APIC frame, if it is too large, it is not read.

The problem is in line 135 of getid3/module.tag.id3v2.php:

`$framedata = $this->fread($sizeofframes); // read all frames from file into $framedata variable`

When the size of the data to read is large because of the image (for example, 100KB), the fread returns a smaller amount (about 15KB), which ultimately reads to an error when trying to read the image from the incomplete $framedata variable.

**Comment by JamesHeinrich** [comment]
$this->fread() should return the requested number of bytes without your proposed workaround.

Are you able to provide a sample file that shows this problem since I cannot replicate the problem, even with a 2MB APIC image.

**Comment by e-gor** [comment]
I attach an MP3 with a cover file that is only 118 KB and which causes the effect told.

[01 - Esan Ozenki.mp3.zip](https://github.com/JamesHeinrich/getID3/files/856047/01.-.Esan.Ozenki.mp3.zip)

The mentioned problem happens to me when I use [owncloud's music app](https://github.com/owncloud/music), which shows and allows playing a music library, with album covers and other things. This app makes use of getID3. And as I said, it does not show album covers if they are larger than 15 KB, because the mentioned function always reads only about 15 KB. It might be caused by some system or PHP config, but however it happens sometimes, and the workaround proposed works well also when this does not happen, so...

**Comment by JamesHeinrich** [comment]
As suspected the provided sample file shows the APIC image just fine on my test system.

The getid3->fread() function already includes a similar block of code (see 0e6c1a3bcef8219fede2c3ead13734296576bce5) which was added to work around fread'ing pipes not immediately returning the expected number of bytes. Which is why I'm confused as to why you're only getting 15kB out of the fread but more with your workaround.

Since I'm unable to replicate the problem, but you can, it would be helpful if you could trace through what's happening in getid3->fread() when analyzing your sample file and why the extant read loop is not getting all the data.

**Comment by e-gor** [comment]
OK, I found the problem. The thing is that the version of the owncloud music app that I am using (which I installed directly from owncloud) is not up to date, and did not have the loop inside the fread function... I guess that it will work OK with that bit of code, without the need of my workaround. You can close the issue and deny the pull request. Sorry...

**Comment by JamesHeinrich** [comment]
Thanks for looking into the issue.
