### ISSUE TITLE
Fatal error: String length exceeded

### ISSUE THREAD

**Issue by slaughter550** [JamesHeinrich/getID3#102]
@JamesHeinrich any help would be appreciated. 

I'm using master and I seem to have encountered this error. I don't quite understand why `fread` is trying to read more bytes than `strlen` can handle but here's the command I'm running.

File: https://s3.amazonaws.com/notebowl/MjAxNy0wMy0xMS0yMC0zNS01OQ/attachment-uploads/4a7URb/wYKQio/fhhIZE.webm

```
getID3()->analyze("/var/www/api/storage/tmp/s3-tmp-95d9e5f5bf29d64ec84e1f7406ccc495")
```

Error:
```
Fatal error: String length exceeded 2^31-2: 72057594037927936 in /var/www/api/vendor/james-heinrich/getid3/getid3/getid3.php on line 1703
```

Stack
```
[2017-03-11 21:49:01] stage.INFO: array (
  0 => 
  array (
    'file' => '/var/www/api/vendor/james-heinrich/getid3/getid3/getid3.php',
    'line' => 1702,
    'function' => 'backtrace',
  ),
  1 => 
  array (
    'file' => '/var/www/api/vendor/james-heinrich/getid3/getid3/module.audio-video.matroska.php',
    'line' => 1238,
    'function' => 'fread',
    'class' => 'getid3_handler',
    'type' => '->',
  ),
  2 => 
  array (
    'file' => '/var/www/api/vendor/james-heinrich/getid3/getid3/module.audio-video.matroska.php',
    'line' => 1285,
    'function' => 'EnsureBufferHasEnoughData',
    'class' => 'getid3_matroska',
    'type' => '->',
  ),
  3 => 
  array (
    'file' => '/var/www/api/vendor/james-heinrich/getid3/getid3/module.audio-video.matroska.php',
    'line' => 1323,
    'function' => 'readEBMLelementData',
    'class' => 'getid3_matroska',
    'type' => '->',
  ),
  4 => 
  array (
    'file' => '/var/www/api/vendor/james-heinrich/getid3/getid3/module.audio-video.matroska.php',
    'line' => 1133,
    'function' => 'getEBMLelement',
    'class' => 'getid3_matroska',
    'type' => '->',
  ),
  5 => 
  array (
    'file' => '/var/www/api/vendor/james-heinrich/getid3/getid3/module.audio-video.matroska.php',
    'line' => 235,
    'function' => 'parseEBML',
    'class' => 'getid3_matroska',
    'type' => '->',
  ),
  6 => 
  array (
    'file' => '/var/www/api/vendor/james-heinrich/getid3/getid3/getid3.php',
    'line' => 462,
    'function' => 'Analyze',
    'class' => 'getid3_matroska',
    'type' => '->',
  ),
  7 => 
  array (
    'file' => '/var/www/api/library/PreviewLibrary.php',
    'line' => 59,
    'function' => 'analyze',
    'class' => 'getID3',
    'type' => '->',
  ),
```

**Comment by JamesHeinrich** [comment]
I've taken a quick look at your sample file and I agree that error is happening. The why of it, however, I'm not sure.  Matroska (EBML) is a pesky format to work with since it's a stream of bits, not bytes, and then you get clever things like variable-size integers to make things even more interesting.

Two possibilities: the file is corrupt or getID3 isn't correctly handling something.
The last element read in has a specified length of 2^56 bytes (inspecting the file at offset 146 you see `01 FF FF FF FF FF FF FF`).
My best guess at this point is that is a magic value to say "unknown" for a live-stream, or something to that effect. getID3 naïvely assumes that the length field is valid and reports it can't seek there because it's beyond the end of the file.

I'm not sure how to fix the problem. If anyone out there wants to contribute a patch I'd be grateful :)
