### ISSUE TITLE
Fatal error in RIFF parser

### ISSUE THREAD

**Issue by andrejasimovic** [JamesHeinrich/getID3#105]
Hi, 
I am experiencing  fatal error with the RIFF parser:  
`PHP Fatal error:  Unsupported operand types in project/vendor/james-heinrich/getid3/getid3/module.audio-video.riff.php on line 431`

It happens with the file which BWFXML contains two **TIMESTAMP_SAMPLE_RATE** tags, and resulting array has TIMESTAMP_SAMPLE_RATE in a form of array [48000,48000], instead of int/double, which causes described fatal error.

I have attached xml file. [BWFXML.txt](https://github.com/JamesHeinrich/getID3/files/870913/BWFXML.txt)  

Please let me know if I can help more with this issue.

**Comment by JamesHeinrich** [comment]
Please try fix in https://github.com/JamesHeinrich/getID3/commit/618baab07808ea6fdfd3cf4e53077d4f31e63c58
Let me know if that does not solve the problem.

I'm still not sure why the XML would contain more than one TIMESTAMP_SAMPLE_RATE tag, but since that's apparently possible I guess getID3 should handle that possibility.

**Comment by andrejasimovic** [comment]
Hi @JamesHeinrich 
Fix you provided solved the problem. 
Thanks a lot!

**Comment by andrejasimovic** [comment]
@JamesHeinrich do you plan on making new release soon, or should I use dev master in composer?

**Comment by JamesHeinrich** [comment]
https://github.com/JamesHeinrich/getID3/releases/tag/v1.9.14

**Comment by andrejasimovic** [comment]
Thanks a lot! 
You rock! 👍 :)
