### ISSUE TITLE
error:all tags erased

### ISSUE THREAD

**Issue by mrcy73** [JamesHeinrich/getID3#106]
Hello,

I want to write only one tag (popularimeter), but all other tags will be deleted!

$tagwriter->overwrite_tags    = true; 
$tagwriter->remove_other_tags = false;
$tagwriter->tag_encoding      = $TextEncoding;
$tagwriter->remove_other_tags = false;

// populate data array
$TagData = array(
//	'title'         => array('Mein Liedel'),
//	'artist'        => array('The Artist'),
//	'album'         => array('Greatest Hits'),
//	'year'          => array('2004'),
//	'genre'         => array('Rock'),
//	'comment'       => array('excellent!'),
//	'track'         => array('04/16'),
'popularimeter'		=>array('email'=>"my.address@gmail.com",'rating'=>255,'data'=>0),

Help me, please.
Thank You!

Greets
Marc

**Comment by JamesHeinrich** [comment]
Writing functions are generally experimental and not well-supported. But try `$tagwriter->overwrite_tags = false;` and see if it does more what you expected.

**Comment by mrcy73** [comment]
Then the tag popularimeter also not written..

**Comment by JamesHeinrich** [comment]
Ah, yes, `$tagwriter->overwrite_tags` deliberately throws an exception because it's not working correctly. The whole ID3v2 tag writing code needs a proper rewrite, but it's not coming any time soon. If someone wants to tackle the project I'm interested in code contributions.

For now your only solution is to read in the existing tag, add/remove/update values as needed, and then write the whole new tag.
