### ISSUE TITLE
Extra 0 at the end of ID3v2 comment

### ISSUE THREAD

**Issue by gino0631** [JamesHeinrich/getID3#121]
It looks like the library returns extra `0` at the end of ID3v2 comment, which gets converted to `&#0;` in `tags_html`.

For example, with [this file](https://github.com/JamesHeinrich/getID3/files/1220544/sample_id3v1_id3v23.zip), containing `COMMENT123456789012345678901` as a comment:
```
  $getID3 = new getID3;
  $out = $getID3->analyze('sample_id3v1_id3v23.mp3');

  $comment = $out['tags_html']['id3v2']['comment'];
  error_log($comment[0]);		// COMMENT123456789012345678901&#0;

  $comment = $out['tags']['id3v2']['comment'];
  error_log(strlen($comment[0]));	// 29
  error_log($comment[0][28] == 0);	// 1

  $comment = 'COMMENT123456789012345678901';
  error_log(strlen($comment));		// 28
```

**Comment by JamesHeinrich** [comment]
getID3 is returning the comment with a trailing null because that's what the comment contains:

![comment](https://user-images.githubusercontent.com/3483435/29252419-0521dd9e-8035-11e7-840f-023166b0ef31.png)

Note the encoding is UTF-16 so two bytes for each character. Note the last two bytes of the selected section (the 68 bytes of data for the COMM frame) are 00 00, a UTF-16 encoded null character.

I'm not sure what program you used to create those tags, perhaps it's incorrectly null-terminating the comment (the description should be null-terminated, the actual comment should not be).
http://id3.org/id3v2.3.0#Comments

**Comment by gino0631** [comment]
Thanks for looking into this. I've used Mp3tag v2.83.

**Comment by JamesHeinrich** [comment]
Let me know if the Mp3tag authors have a different opinion about the issue.

**Comment by gino0631** [comment]
It looks like they call it a [feature](https://forums.mp3tag.de/index.php?showtopic=22788) :worried:

**Comment by cbj4074** [comment]
I'm using the `mid3v2` CLI tool provided with https://github.com/quodlibet/mutagen , and its tags exhibit the same problem when parsed with getID3.

It's frustrating that the relevant specification is written in such a way that is ambiguous, thereby causing one developer to implement it differently than another.

To quote Florian, from https://community.mp3tag.de/t/x-trailing-nulls-in-id3v2-comments/19227/4 :

> This can give the impression that all strings are terminated. In fact, some developers implemented in exactly this way (e.g., Apple iTunes or foobar2000), whereas others are not terminating the strings (e.g., Windows Media Player).

Given this most unfortunate state of affairs, what are end-users to do?

I'd "complain" to the Mutagen author, but I suspect I'll be met with insistence that the specification is being followed, and getID3 has it wrong.

Curious if your thoughts regarding the specific nature of this debate have changed since your last post in this thread, @JamesHeinrich . Have you read the comment that @gino0631 cited? Are you willing to make the concession put forward therein?

Thanks in advance!

**Comment by JamesHeinrich** [comment]
I have made change https://github.com/JamesHeinrich/getID3/commit/127aac6772a4daeb42828c0d5956c0ef5cbf6390 to remove null terminator if present.

**Comment by cbj4074** [comment]
Thanks so much for lightning-fast reply and remediation @JamesHeinrich ! I really appreciate it!

Just for the record, and so I understand the specification, is your contention still that the libraries that include the trailing null are in violation of the spec? Or is the spec ambiguous?

Thanks again!

**Comment by JamesHeinrich** [comment]
The ID3v2.3 was less ambiguous in this point, but ID3v2.4 spec that Florian quoted makes it less clear. I still think the ID3v2 author's intent was that the comment string _not_ be null-terminated, but since there are multiple variants in the wild I guess it's best to support what's out there, regardless of what the specs intended.

For a format that has always had quite extensive documentation, ID3v2 must hold some kind of record for implementations in violation of the specs and/or variant interpretations of said specs.

**Comment by cbj4074** [comment]
Excellent; the clarification is hugely helpful. And somewhat comical. :D

One other thought/question:

As I describe in https://github.com/quodlibet/mutagen/issues/379 , I notice that the frame values suffer from the same problem. For example, the value at `['id3v2']['TPE1'][0]['data']`.

Do these warrant the same "triage"/workaround?

**Comment by JamesHeinrich** [comment]
In https://github.com/JamesHeinrich/getID3/commit/4c2c7741c668d60bb1401ac4110c4d2dcd802ae7 I have extended the remove-trailing-nulls-if-applicable code to all other ID3v2 frame types where I think it's applicable. If I missed something please let me know.

**Comment by cbj4074** [comment]
Perfect! Every instance I had noticed now appears to be fixed, but I'll post an update if I happen upon any others.

Thanks again for your prompt replies and willingness to compromise with the other implementations that are in play.
