### ISSUE TITLE
[error] [php] Undefined index: bsmod in getid3/module.audio.ac3.php:442

### ISSUE THREAD

**Issue by ReinVelt** [JamesHeinrich/getID3#128]
The library worked without problems, but the last days i get some errors in my log:

> [error] [php] Undefined index: bsmod in getid3/module.audio.ac3.php:442

I get these errors after calling the following code:

```
 public function getVideoDuration() {
        $getId3 = new getID3();
        $fileInfo = $getId3->analyze($this->getVideoUri);
        return $fileInfo['playtime_seconds'];
    }
```

$this->getVideoUri points to a valid video. I get this error with different videos

**Comment by JamesHeinrich** [comment]
I would speculate that the videos that you are having problems with use [EAC3](https://en.wikipedia.org/wiki/Dolby_Digital_Plus) for the audio.

I took the easy way out and just wrapped a conditional if-defined around the line in question, which should be fine since the value set on line 442 isn't used elsewhere that I can see.

**Comment by ReinVelt** [comment]
Thanks for this fix. It was solved within 2 hours, so i owe you a beer for your rapid response
