### ISSUE TITLE
Mp3 Player Issues

### ISSUE THREAD

**Issue by falconxxx** [JamesHeinrich/getID3#129]
AFter splicing mp3 files and joining them, I tested the mp3 file using groove music player on windows 10 it skipped the 2nd mp3 I joined and when I played mp3 file on VLC it worked fine,
Is this issue my fault or this?

**Comment by JamesHeinrich** [comment]
If "Groove" skipped the second MP3, then it's broken.  MP3 players are supposed to scan through the file, find any playable sequence of MPEG audio data, and skip any garbage anywhere in the middle of the file. It's a bitstream format designed to handle mid-stream corruption which is why it should be trivial to append MP3 files together and get something playable. Perhaps not perfect in terms of file structure, but as far as the audio that comes out no matter how you stick them together it should work perfectly. If not, then Groove is doing something wrong.
