### ISSUE TITLE
Timestamp and remote files?

### ISSUE THREAD

**Issue by seabasss** [JamesHeinrich/getID3#134]
Is it possible to extract the timestamp from wav files with this? If yes, how?
If I want to do it on a file on a different server, does it have to be downloaded locally first?

**Comment by JamesHeinrich** [comment]
If you mean a timestamp embedded in the RIFF header (e.g. CART, BWF) by the recording software, then yes getID3 can extract that.
getID3 only operates on local files, so you will need to copy it locally first. You can probably get away with only copying the first little bit of the file (32kB should probably be fine), with the caveat that playtime and possibly bitrate may be inaccurate without the complete file.

**Comment by seabasss** [comment]
Thank you! Do you have a quick example of how I get the timestamp? Like `getID3('wav.wav', 'timestamp')`. What's the actual term for the timestamp?

I actually only need the timestamp and the duration. Do you know of a quick and efficient way to retrieve that on a remote file without downloading the whole file?

**Comment by JamesHeinrich** [comment]
Just double-checking we're talking about the same thing, that you do mean the recording software timestamp (as stored in the BWF chunk), which not all WAV files will contain (in fact most WAV files not recorded with studio-grade hardware/software will _not_ have it). As opposed to the file modification date (which will exist for any file)?

For the playtime you will need to know the full filesize, even if you only copy a small part of the file.
There are some sample remote_filesize functions on http://www.php.net/manual/en/function.filesize.php if you don't already have one of your own.

```
$url = 'http://example.com/file.wav';
$filesize = filesize_remote($url); // use your own remote filesize function here

// copy 32kB of URL to temp file
$tempfilename = tempnam();
$fp1 = fopen($url, 'rb');
$fp2 = fopen($tempfilename, 'wb');
fwrite($fp2, fread($fp2, 32768));
fclose($fp2);
fclose($fp1);

require_once('../getid3/getid3.php');
$getID3 = new getID3;
$ThisFileInfo = $getID3->analyze($tempfilename, $filesize); // pass remote filesize otherwise duration will be incorrect without copying entire file.

// delete temp file
unlink($tempfilename);

// do something with the data.
// you should add a check that it does exist since its presence is not guaranteed in all WAV files
echo $ThisFileInfo['riff']['WAVE']['bext'][0]['origin_date']."\n";
echo $ThisFileInfo['riff']['WAVE']['bext'][0]['origin_time']."\n";
echo date('j M Y g:i:sa', $ThisFileInfo['riff']['WAVE']['bext'][0]['origin_time_unix'])."\n";
```

**Comment by seabasss** [comment]
Wow, thanks for the help! :)

Yes, I'm thinking of the timestamp from recording software. What do I ask for to get that? I don't need the modification date. Is that what your code is requesting?

But you just need the filesize to calculate the playtime? The file can be empty or packed with audio info and still be the same filesize?

...

I had to change it to `tempnam("tmp", "FOO")` to get around an error. And after that I got `Undefined index: riff`, but I guess that is because of what you said `you should add a check that it does exist since its presence is not guaranteed in all WAV files`?

I found a script that got me the remote file size (but it doesn't seem to work on dropbox links. I guess since they are wrapped in a container of some sort. If you have any ideas on that one it's awesome but that's another story). Does it still have to download the whole audio file to determine the file size?

`function remote_filesize($url) {
    static $regex = '/^Content-Length: *+\K\d++$/im';
    if (!$fp = @fopen($url, 'rb')) {
        return false;
    }
    if (
        isset($http_response_header) &&
        preg_match($regex, implode("\n", $http_response_header), $matches)
    ) {
        return (int)$matches[0];
    }
    return strlen(stream_get_contents($fp));
}`

Thanks for your time!

**Comment by JamesHeinrich** [comment]
The BWF datestamp is returned in `$ThisFileInfo['riff']['WAVE']['bext'][0]['origin_date']`
The BWF timestamp is returned in `$ThisFileInfo['riff']['WAVE']['bext'][0]['origin_time']`
These two are also combined and parsed into a UNIX timestamp for your convenience (to use PHP date functions to manipulate in the format of your choice) in `$ThisFileInfo['riff']['WAVE']['bext'][0]['origin_date_unix']`

If you're not copying the entire file you need to tell getID3 the original filesize (as the second parameter of getID3->analyze() ) so that the bitrate can be calculated (in most cases). If you're passing the filesize parameter it doesn't matter if the file snippet you're analyzing is actually that size or not.

If you're not finding the 'riff' key then something's not right, because that _will_ be in every WAV file.

I would suggest copying one file locally and make sure you're finding the data you want with a local file first before introducing the complexity of a remote filecopy.  You may find demo/demo.browse.php to be a convenient way to see what data is being returned where for any particular file.

**Comment by seabasss** [comment]
Thank you. I hacked a `$ThisFileInfo['riff']['WAVE']['bext'][0]['origin_time']` part into the browse demo file and now it returned `19:13:31`.

One last question. The timestamp I'm expecting for that file is `01.23.18.11` (without the subframes if that's also in there). Do you think the `19:13:31` is what I'm looking for, but needs to be converted somehow?

**Comment by JamesHeinrich** [comment]
Not sure why you'd want to "hack" something into demo.browse, since it displays it all nicely for you in your browser.

The origin_(date|time) is the date&time that the audio was recorded at. 19:13:31 is roughly 7:13pm on whatever date is in origin_date. It is not a timecode, it is real clock time.

Without seeing what data is in your file, or knowing what data you're looking for, it's hard to comment further. Please open demos/demo.browse.php in your browser, navigate to the file in question, and you should see all the data parsed by getID3. If you need further help, please save the HTML output and attach it here so I can see what's in your file.

**Comment by seabasss** [comment]
We're probably talking about different things. I'm looking for the timecode position where it was located on a timeline inside a DAW. If that makes any sense. I don't know if that is stored in samples or HH:MM:SS:FF and if it's relative or absolute. Let's say an audio file is exported out of Logic PRO. If I open that file in Pro Tools I can snap it into the same recording position based on a value that got saved into the audio file somewhere.

Yes, right before reading your latest post I realized that I can click on the wav file filename in getID3 and bring up detailed data! That's why I hacked it in. No need indeed! Thanks for the patience.

Maybe one of the the `avdataend`, `avdataoffset`, `offset` or `time_reference` is what I'm looking for.

[Here's a screenshot of the result](https://www.dropbox.com/s/lv7qr9wfn6o0sfz/wav-data.png?dl=0)

**Comment by seabasss** [comment]
I bounced out a bunch of audio files from different spots and it looks like `time_reference` contains what I need in samples! I can use that along with the sample rate to figure out the timecode!

Thank you so much! :)

**Comment by JamesHeinrich** [comment]
`avdataoffset` and `avdataend` are getID3-specific values, where getID3 thinks the audio/video data starts/ends (without headers and tags), for all file formats. You can ignore them. `offset` will appear in many places and is generally where that chunk of metadata exists in the file, and can also be ignored.

I suspect [riff][WAVE][bext][0][time_reference] is probably what you're looking for, and is [defined](https://tech.ebu.ch/docs/tech/tech3285.pdf) as 

> a 64-bit value which contains the first sample count since midnight. The number of samples per second depends on the sample frequency

So in your example, 258299490 / 48000 = 5,381.239375 = 1h29m41.24s (not sure if frames should be 24/25/30/other)
