### ISSUE TITLE
Audio duration isn't quite right sometimes

### ISSUE THREAD

**Issue by agamemnus** [JamesHeinrich/getID3#161]
I am not sure why. This is an mp3 file. Temporary link: https://tinyurl.com/y77jabev

getID3 reports 1875.9835 seconds. But the actual length seems to be 1875.957551 seconds. I think I am using the latest code.

**Comment by JamesHeinrich** [comment]
I believe in this case the discrepancy arises from the VBR header frame, which is the first frame of the audio data, specially crafted to contain no actual audio data but contain encoder metadata, most notably for VBR encoding but also used by some encoders (including LAME) for CBR encodings. In most applications the single frame of data, which lasts ~0.026s, is insignificant whether it is prepended to the audio as 0.026s of silence, or ignored entirely.  I'm not sure which program you used to determine the 1875.957551 duration, presumably it is something fairly modern that understands MP3 VBR header frames and deliberately ignores them as non-audio data. Older audio software (e.g. I tried Cool Edit 2000) will interpret the VBR header frame as silent audio data and report 1875.983 duration.

I have patched module.audio.mp3.php to also ignore the VBR header frame (if present) to show the more-correct shorter 1875.9575 duration. I considered but decided not to adjust the [avdataoffset] key since it would make it difficult to find the VBR header.

Please try the latest version and let me know if the issue is not fixed.
https://github.com/JamesHeinrich/getID3/commit/379f48c93ab75eda8d954f9334669534b3021eb6

**Comment by agamemnus** [comment]
Thanks.. the duration value in the Chrome browser (Javascript) wasn't lining up.
