### ISSUE TITLE
Cant write field Year on ID3v2.3/2.4

### ISSUE THREAD

**Issue by ArvyRogerio** [JamesHeinrich/getID3#162]
Hello, when I use getid3_writetags, I can set the field "year" on ID3v1 but not on ID3v2.x
Using WinAmp I can see the correct year on "id3v1" tab. But it's empty on "id3v2" tab.

Using this online reader (v2):
http://web.ist.utl.pt/antonio.afonso/www.aadsm.net/libraries/id3/
it returns an empty year field. 

Any ideias?
Thank you.

**Comment by JamesHeinrich** [comment]
That would of course depend on how you're writing the tags. Are you sure you're writing both ID3v1 and ID3v2?  You can see [demo.simple.write.php](https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.simple.write.php) as a starting point (being sure to have `$tagwriter->tagformats = array('id3v1', 'id3v2.3');` or equivalent).

If you think your code should be writing the year to ID3v2 but isn't, please post the relevant part of your tag-writing code.

Also remember you can easily see what data is present in any file with demos/demo.browse.php (in your browser).

**Comment by JamesHeinrich** [comment]
One minor thing that jumped out at me:
```
$tagwriter->tagformats=array('id3v1','id3v2.3','id3v2.4');
```
There can only be one ID3v2 tag on a file, you can choose between ID3v2.2 (not recommended), or ID3v2.3 or ID3v2.4, but you can't have more than one. With the code as you have it the tag will be written as ID3v2.3, then immediately deleted and replaced with the ID3v2.4 version, but since this is unexpected input the tag writer will not be correctly initialized leading to undefined behaviour, in this case your year field not showing up correctly.  Pick either ID3v2.3 or ID3v2.4, but not both, and your tag should show up correctly.

I have patched write.php to detect if you try to write more than one ID3v2 tag version at once and fail with an error:
https://github.com/JamesHeinrich/getID3/commit/2a11c52e7ca2b63418da96feb543f8666fa5d924

**Comment by ArvyRogerio** [comment]
Hello James,
thank you, changed to array('id3v1','id3v2.3') and it's working correctly now.

Final question: why not 2.2? And better 2.3 or 2.4? 2.3 is more used? I don't know about the versions.

**Comment by JamesHeinrich** [comment]
[ID3v2.3](http://id3.org/d3v2.3.0) (published 1999-Feb-01) is by far the most common version in use in the wild.
[ID3v2.4](http://id3.org/id3v2.4.0-structure) is a little newer (2000-Nov-01), quite similar to v2.3

[ID3v2.2](http://id3.org/id3v2-00) is the oldest published standard (1998-Mar-26), and differs significantly from v2.3/2.4, notably in the use of 3-byte fields instead of 4-byte, etc.  It's not uncommon to find an ID3v2-supporting program have poor support for ID3v2.2 (usually in the form of expecting the structure to match later versions, which it does not).

Anecdotally, it would seem that ID3v2 got a lot of attention in 1999-2000 when support was added to many programs. By this time ID3v2.3 had replaced v2.2 and so became the most-implemented version.

So I would generally suggest ID3v2.4, unless you have need to support older software, in which case ID3v2.3 may be slightly more compatible. But avoid ID3v2.2 unless you have a _very_ specific need to do so.

**Comment by ArvyRogerio** [comment]
Perfect, thank you for the high detailed explaination!
