### ISSUE TITLE
structure.txt: audio::streams & flac codec

### ISSUE THREAD

**Issue by viamuli** [JamesHeinrich/getID3#169]
The index ["audio"]["streams"] does not exist in structure.txt

Would be really helpful to have an explanation on this index since it appears that analyzed flac files do not have the "codec" index within the streams but wav files do have this index set ("pcm"). Should this index not always be set to "pcm" while analyzing flac files, too?

**Comment by JamesHeinrich** [comment]
The audio codec exists in WAV because the RIFF/WAV container supports different codecs. Most commonly it's uncompressed PCM, but it can also be ADPCM, µLaw, MP3, etc.  FLAC files on the other hand _only_ contain FLAC audio. I suppose I could hardcode audio.streams.codec="flac" for all FLAC files, but I don't think it wouldn't add much since it's constant for all FLAC files.
