### ISSUE TITLE
Composer version of getID3 throw an error when copyTagsToComments() is called.

### ISSUE THREAD

**Issue by blakyris** [JamesHeinrich/getID3#209]
I have the git version to code my own parser to fit my needs but when I deploy the code into my app which uses the composer version of getID3() copyTagsToComments() returns error with message : "Can't determine file format." The file is MP3.

[track.zip](https://github.com/JamesHeinrich/getID3/files/3906090/track.zip)

**Comment by JamesHeinrich** [comment]
As is not uncommon in MP3 files (due to plenty of ID3v2-writing software out there that doesn't always conform to specs), your sample file has garbage at the before the audio data. Quoting the getID3 warning:
```
Unknown data before synch (ID3v2 header ends at 129034, then 184 bytes garbage, synch detected at 129218)
```
More specifically, you have 129218 bytes of valid ID3v2 (including cover art and padding), and then another ID3v2 tag, 184 bytes in length, and then the MP3 audio data. Most likely whatever tagging program added the current large ID3v2 tag just prepended in on the front of the file and didn't check for or remove the existing ID3v2 tag. Or a previous tagging program did that, and the most recent tagging simply modified the first ID3v2 tag.  To be clear: There is only allowed to be a single ID3v2 tag at the beginning of a file (at the end it's a little ambiguous with ID3v1, Lyrics3 and APE competing for the same end-of-file spot; by convention ID3v1 must go last, Lyrics3 must go last or immediately before ID3v1, APE will be flexible enough to be at the end or before either/both of the others).

Putting garbage in front of the MPEG-audio bytestream makes it very difficult to differentiate from random data. If we know (or at least have a high suspicion) that the file is in fact MPEG-audio we can spend extra time walking through byte-by-byte until we find a string of valid MPEG audio data frames, but this is a slow process so we really don't want to do this for every unrecognized file, only those where we already expect the file to be MPEG-audio but it isn't detecting as such.
This is what's done for files named .mp3 (and similar) in GetFileFormat [getid3.php::1336-1342](https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L1336-L1342). If your file is named .mp3 at the time of analysis it should be processed correctly. If it has some random name (e.g. temporary file) then it would be rejected as unknown format as you describe.

The easy fix is to rename temporary files you expect to be MP3 format to end in .mp3. The more complex fix involves setting [$allow_bruteforce in module.audio.mp3.php](https://github.com/JamesHeinrich/getID3/blob/master/getid3/module.audio.mp3.php#L33) prior to scanning files you expect to be mp3-with-garbage.

**Comment by blakyris** [comment]
Thanks so much for your explainations, yeah I'm working with temporary files without extension in the file name.
