### ISSUE TITLE
Files not readable

### ISSUE THREAD

**Issue by sgt-spike** [JamesHeinrich/getID3#231]
Not sure what's happening.

As I open demo.browse.php, I can see the directory where my files are at.  I can open that directory and see all the video files (mp4, m4v).  I can click on each file and it will show all the tags arrays.

I edited the demo.basic.php, pointing the $file directly to a video file and get the tags array for that file.
However, when I create my own script using either opendir() or scandir(), I get an error saying the files cannot be read.  I'm not sure what's going on to understand the error.

All I want to do is read some of the tags into a db.

```
include "../php/getID3/getid3/getid3.php";
//require_once "connection.php";

ini_set("display_errors", 1);
error_reporting(E_ALL);
$PageEncoding  = "UTF-8";
$search_dir = "../../../movies";
$getID3 = new getID3;
//$movies_dir = scandir($search_dir);
$dhandle = opendir($search_dir);

$getID3->setOption(array("encoding" => $PageEncoding));
//create a table header
print "<hr><h2>Files</h2><table cellpadding=\"2\" cellspacing=\"2\" align=\"left\"><tr><th>File Name</th><th>Movie Name</th><th>Description</th></tr>";

if ($dhandle) {
   // loop through all of the files/dir in the movie directory
   while ( false !== ($dmovie = readdir($dhandle)) ) {
         // if the element is a directory, and
         // does not start with a '.' or '..'
         // passing this element as a parameter
         if ( is_dir( "{$search_dir}/{$dmovie}" ) ) {
            if (($dmovie != '.') && ($dmovie != '..')) {
                // opens the movie subdirectory
                if ($dh = opendir( "{$search_dir}/{$dmovie}" )) {
                    // loops through all files in movie subdirectory
                     while (($file = readdir($dh)) !==false) {
                        if (is_readable($file)) {
                           # code...
                           echo filetype($file).'File is readable <br>';
                           $tags = $getID3->analyze($file);
                         $getID3->CopyTagsToComments($tags);
                        } else {
                           echo filetype($file).'File is not readable <br>';
                        }
                    }
                    closedir($dh);
                }
            }
        }
    }
    closedir($dhandle);
}
print '</table>';
```

I have my files on a linux server

**Comment by JamesHeinrich** [comment]
Presumably you mean you're getting the "File is not readable" message from the else part of [is_readable](https://www.php.net/manual/en/function.is-readable.php)($file). It could fail because the file doesn't exist, or because you don't have permission to read it. At a quick glance at your code I'd say that you're not setting $file correctly, you're just getting it from readdir which returns a base filename (e.g. "video.mkv") not a full filename ("/path/to/the/filename.mkv"). It should probably include some directory information like $search_dir/$dmovie/$file.

In any case, this looks like it's outside the scope of getID3 support.
