### ISSUE TITLE
analyze on vorbiscomment returning "Array" as a string for some tags

### ISSUE THREAD

**Issue by lachlan-00** [JamesHeinrich/getID3#248]
Hi, I'm trying to track down why my ogg files are just returning the string "Array" for a lot of the tags. Could this be as simple as the vorbistags on the file itself?

I read the ogg file
```
$this->_getID3 = new getID3();

$this->_getID3->option_md5_data        = false;
$this->_getID3->option_md5_data_source = false;
$this->_getID3->option_tags_html       = false;
$this->_getID3->option_extra_info      = true;
$this->_getID3->option_tag_lyrics3     = true;
$this->_getID3->option_tags_process    = true;
$this->_getID3->option_tag_apetag      = true;
$this->_getID3->encoding               = $this->encoding;

$this->_raw = $this->_getID3->analyze($file);
```

i try to parse them
```
if (is_array($this->_raw['tags'])) {
	foreach ($this->_raw['tags'] as $key => $tag_array) {
		switch ($key) {
			case 'vorbiscomment':
				debug_event('vainfo.class', 'Cleaning vorbis', 5);
				$parsed = $this->_cleanup_vorbiscomment($tag_array);
			break;
```

Then i try a print_r() in the function _cleanup_vorbiscomment
```
[encoder] => Array([0] => Lavf54.3.100)
[format] => Array([0] => Array)
[length] => Array([0] => Array)
[mtime] => Array([0] => Array)
[size] => Array([0] => Array)
[md5] => Array([0] => Array)
[crc32] => Array([0] => Array)
[sha1] => Array([0] => Array)
[source] => Array([0] => original)
```

**Comment by JamesHeinrich** [comment]
In general tag data across all formats should be in the format
`[tags][<tagformat>][<tagkey>][<index>] = string`
e.g. `[tags][vorbiscomment][artist][0] = 'someone'`
They keys you describe are unusual (metadata that might normally be derived from the file itself, as opposed to typical content metadata like artist and title) but by no means illegal.
Can you please send this (or similar) sample file to info@getid3.org so I can take a look?

**Comment by lachlan-00** [comment]
No problem. Nextcloud link incoming

**Comment by JamesHeinrich** [comment]
Thanks for the sample file(s). I took a look at the first one and the answer became clear, and simple: it's returning the value "Array" for some tag entries because... that's what's stored in the tag -- the 5-character English word "Array". If we look inside the first few bytes of the first sample file, we see "Array" several times (for tags FORMAT, LENGTH, MTIME, SIZE, MD5, CRC32, SHA1):
![git248b](https://user-images.githubusercontent.com/3483435/83019993-d81ffb80-9ff5-11ea-8f8a-c4e73b86bfa8.png)

Whatever program was used to tag these files appears to have been passing incorrect parameters to the writing function (an array instead of a string) and so the value apparently got written as "Array" in the tag.

**Comment by lachlan-00** [comment]
excellent. thank you for looking! i was wondering if it was the code but i'm pretty sure these were cli converted a long time ago.
