### ISSUE TITLE
DSD Format dff

### ISSUE THREAD

**Issue by marcbth** [JamesHeinrich/getID3#249]
Hello,

is it possible to add the DSD format dff?

Have a nice weekend.

Cliff

**Comment by JamesHeinrich** [comment]
Do you have a sample file?

**Comment by marcbth** [comment]
of course

I can send it via wetransfer

http://www.sonicstudio.com/pdf/dsd/DSDIFF_1.5_Spec.pdf

**Comment by marcbth** [comment]
https://dsd-guide.com/sites/default/files/white-papers/DSDIFF_1.5_Spec.pdf

I send it on your emailadress info@silisoftware.com

Cliff

**Comment by JamesHeinrich** [comment]
Thanks for the sample file and especially for linking to the documentation, very helpful.
(incidentally info@getid3.org would be the preferred email address for getID3 related stuff, but it all comes to me so that's fine).

DSDIFF support added in https://github.com/JamesHeinrich/getID3/commit/cde8ac014c7d8fce9af004974eff400a9ee348a6
