### ISSUE TITLE
Stable 2.0 release date

### ISSUE THREAD

**Issue by davidromani** [JamesHeinrich/getID3#252]
Hello.

It's planned to release a stable 2.0 version? I usually work with stable dependencies in my projects and it would be nice to include this one.

Thanks.

**Comment by JamesHeinrich** [comment]
My only work is on the 1.x branch. Every now and then some other contributors port some changes to the 2.0 branch, but for my purposes 2.0 has been "abandoned" since 2010.

**Comment by StudioMaX** [comment]
I sometimes make changes to the `2.0` branch, but usually this is just a cherry-picking commits from the `master` branch, making them PSR-4-compatible. I use this `2.0` branch in my projects, but most likely only few people use it, because @JamesHeinrich supports only version `1.x`.

And yes, there have been many attempts to create version 2.0 by different contributors, but all of them have not been supported for a long time. The official site says about version 2.0
> PHP v5.0.5 (or newer) for getID3() v2.0.0-b6 (Note: this is a feature-incomplete beta version, not in active bugfixing/development)

But in fact, in this repository version 2.0 is a completely different project, which was made some time ago for compatibility with Composer autoloading and PSR standards.

If you really use branch `2.x`, then I can synchronize all the latest commits from the `master` branch and release it as beta 2, but no more. Most likely, only `1.x` will remain the officially supported version in the near future.

**Comment by JamesHeinrich** [comment]
Thanks @StudioMaX. I took the liberty of editing your comment to point to getid3.org instead of sourceforge as getid3.org is the real "official website" (and getid3.sf.net is currently a mirror of it).

**Comment by davidromani** [comment]
Ok, thanks for your answers and my apologies because I didn't read about 2.0 "deprecation" before.

@StudioMaX please, can you do it?
