### ISSUE TITLE
getID3 couldn't return correct Unicode from comment

### ISSUE THREAD

**Issue by MahdiPishguy** [JamesHeinrich/getID3#262]
in this code i try to get correct `utf-8` charset from comment of mp3 file. but that return incorrect charset as ????? ?? ????????

```php
$getID3 = new getID3;
$getID3->encoding_id3v1 = 'UTF-8';
$getID3->encoding = 'UTF-8';
$getID3->encoding_id3v1_autodetect = true;
$getID3->setOption(array('encoding' => "UTF-8"));
$mediaInformation = $getID3->analyze($public_html . $filePath . $fileName);
if(!empty($mediaInformation['tags'])) {
    RadioChannelsFiles::create(
        [
            'playlist_id' => $channel->id,
            'file_orig_name' => explode('.', $file->getClientOriginalName())[0],
            'filename' => $fileName,
            'file_path' => $filePath,
            'duration' => $mediaInformation['playtime_string'],
            'keywords' => htmlspecialchars($mediaInformation['tags']['id3v1']['comment'][0], ENT_QUOTES ,'UTF-8', true),
             //'keywords' => iconv('ISO-8859-1','UTF-8',$mediaInformation['tags']['id3v1']['comment'][0]),
            'file_size' => $this->readableBytes($mediaInformation['filesize']),
        ]
    );
}else{
    
}
```

**Comment by JamesHeinrich** [comment]
ID3v1 doesn't contain character encoding information. It was originally expected to contain ISO-8859-1 but regionally people have tagged files with local character sets representing their non-latin charactersets. But it's difficult/impossible to identify which character set is actually used. Honestly I've never actually seen an ID3v1 tag using UTF-8 encoding (likely due to limited length, 30 characters could be cut to much less).

Your code is showing that you expect the ID3v1 tag to contain UTF-8 encoded text (`$getID3->encoding_id3v1 = 'UTF-8'`), which I would find unusual (I've never seen a file tagged that way). If you know what encoding the ID3v1 tag uses then you can set that, otherwise omit that line to leave it at the default ISO-8859-1.

If you're still having trouble and you want to email me a link to a sample file, go ahead.

**Comment by JamesHeinrich** [comment]
I took a look at your sample file. It includes both ID3v1 and ID3v2. They contain mostly the same data, but with some differences.
Artist, Title, Album are all written in latin characters.
I guess technically Year is in Arabic numerals but they're simply universal now.
Curiously the Genre is set (presumably in error) to "2019" which is assigned as "Other" in ID3v1.

The only major difference between ID3v1 and ID3v2 data is in the Comment. The comment is represented correctly in ID3v2 as `سلام+خوبی`, but whatever program was used to tag this file could not represent those characters in ISO-8859-1 so it chose to transliterate the comment as best it could, and the comment is written to ID3v1 as a literal `????+????`. So it's not any kind of decoding issue in getID3, that's just what's in the tag.

In general, for any type of file analyzed by getID3, you should be looking in the unified `[comments]` array rather than at a specific tag value like `[tags][id3v1]`. The `[comments]` key contains a unified merged set of comments for all tag formats that may be present in any type of file, so you don't have to worry if it has ID3v1, ID3v2, APE, Lyrics3, FLAC, Vorbis, etc. Duplicate values from different tag types are merged, and semi-duplicate values (where ID3v1 contains a truncated version of the text in ID3v2 for example) are also merged to the longer value. For your convenience there is also a pre-encoded `[comments_html]` key for situations where you need it (as in your example). The `[comments]` key also contains the special key `[comments][picture]` for all tag format that contain any embedded images as these tend to be scattered in hard-to-find locations in various tag formats.

My suggested modifications for your code:
```$getID3 = new getID3;
$mediaInformation = $getID3->analyze($public_html . $filePath . $fileName);
$getID3->CopyTagsToComments($mediaInformation);
if (!empty($mediaInformation['comments'])) {
	RadioChannelsFiles::create([
		'playlist_id'    => $channel->id,
		//'file_orig_name' => explode('.', $file->getClientOriginalName())[0],
		'file_orig_name' => substr($file->getClientOriginalName(), 0, strrpos($file->getClientOriginalName(), '.')),
		'filename'       => $fileName,
		'file_path'      => $filePath,
		'duration'       => $mediaInformation['playtime_string'],
		//'keywords'       => htmlspecialchars($mediaInformation['tags']['id3v1']['comment'][0], ENT_QUOTES ,'UTF-8', true),
		'keywords'       => $mediaInformation['comments_html']['comment'][0],
		'file_size'      => $this->readableBytes($mediaInformation['filesize']),
	]);
} else {
}```
Note that I also suggested a change for `file_orig_name` as your code would get confused by any filename with a period in it (e.g. "Mambo No. 5.mp3" would return "Mambo No" instead of "Mambo No. 5")

**Comment by MahdiPishguy** [comment]
@JamesHeinrich Thanks a lot. now that return arabic characters to such as `&#1587;&#1604;&#1575;&#1605;+&#1582;&#1608;&#1576;&#1740;` instead of `?????`
