### ISSUE TITLE
Issue in joining two MP3

### ISSUE THREAD

**Issue by Diwakar14** [JamesHeinrich/getID3#272]
Time get calculate but the MP3 does not plays after the first MP3, it happens to few MP3. Some are correctly joined.

**Comment by JamesHeinrich** [comment]
Please show what code you're using to join the two MP3s, and provide a link to a sample joined file that doesn't play correctly.
I'm surprised that an MP3 wouldn't play at all, since by format definition players need to skip over any unexpected or malformed data, so they're hard to break.

**Comment by Diwakar14** [comment]
**i used this code **
https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.joinmp3.php

**This is how i called that function**
CombineMultipleMP3sTo('sample2.mp3', array(array('assets/signature/Sample3.mp3',0,0), array('public/Diwakar/songs/sample1.mp3',0,0)));

**Comment by JamesHeinrich** [comment]
Thank you for the sample files. I tried with your files and code and got the identical output to sample2.mp3, and that plays fine for me here in some of the software I tried (Winamp, VLC, BSplayer, etc). However, I found that Windows Media Player (v12) and Chrome (v86) both play the 8 seconds of the first component MP3 and then stop. Looking at the provided files, we see that sample3 is normal 44.1kHz, but sample1 is 32kHz.  The nature of MP3 allows for bitrate changes at every frame, but changing the sample-rate or number of channels in the middle of a file is not expected. Some software (as noted: Winamp, VLC, BSplayer, CoolEdit) I tried did successfully play the combined file (generally visually "restarting" the playbar from zero after the first 8 second segment), but I wouldn't count on all software being able to do so, as you have discovered.

Since presumably you'll be prepending that 8-second sample3 to many files, you'll need to transcode either the soundbite or the music such that they're the same sample rate. Since 44100 is CD-audio standard that would be my suggestion, but it shouldn't matter either way as long as all the component MP3s you're joining are the same sample rate.
