### ISSUE TITLE
Some mp3 CBR files are incorrectly detected as VBR.

### ISSUE THREAD

**Issue by kgroeneveld** [JamesHeinrich/getID3#287]
Here is a download link (good for 30 days) for three example CBR files encoded by ffmpeg that are detected as VBR:
https://ufile.io/f/27zkt

The files include:
ffmpeg_128k_cbr.mp3
ffmpeg_64k_cbr.mp3
ffmpeg_64k_cbr_corrupt.mp3

The last one I purposely changed one byte in the first audio frame to help test handling with bad data.

I plan to also submit a related PR which goes into more detail and includes a potential fix.

**Comment by JamesHeinrich** [comment]
MP3 files are simply a sequence of audio frames. They need to be the same general specification (MPEG layer, channels, frequency) but are free to vary in bitrate every frame. The optional VBR header frame gives a place to put some information about the whole-file average bitrate and similar. Some extensions to this header frame (e.g. LAME) allow for additional information about the VBR method chosen (which may include CBR), but otherwise it's hard to differentiate between a true CBR file, a VBR file where most (but not all) of the frames are the CBR bitrate (but the others balance above and below the average bitrate), or a wide-ranging VBR file with a full spread of frame bitrates where the average bitrate happens to match a common CBR rate. The only real solution is to walk through the entire file and count the bitrate of each frame. This will give you a perfectly accurate picture of the bitrate distribution in the file, but is also more resource-intensive and disabled by default in getID3.

I'm not sure that your change makes any real improvements, so I'm going to opt out of including it for now.

**Comment by kgroeneveld** [comment]
Perhaps some background on why I care about this issue.

The site [librivox.org](https://librivox.org) uses getID3 to read and edit MP3 tags and for determining MP3 file specifications. Volunteer readers are supposed to upload MP3 files that are mono 128k CBR. These eventually get sent to [archive.org](https://archive.org) which derives a couple lower quality formats as well. When the files are not 128k CBR this process can break down. So before librivox.org uploads the files to archive.org it tries to verify they really are 128k CBR. However getID3 is identifying some files produced by popular encoders such as ffmpeg as VBR when they really are CBR.

I realize the only way to be 100% sure is to scan the entire file. But getID3 will already identify many other CBR files as CBR without actually scanning the whole file.

Do you have any suggestions on ways to handle this issue?

**Comment by JamesHeinrich** [comment]
getID3 scans a small number of frames at the start of the file to ensure that what appears to be the start of audio data isn't just random data. It may be possible to use this brief analysis, in conjunction with VBR-header projected bitrates, to better flag CBR files with a Xing (VBR) header. I'll look into this further and see if I can make something workable.

**Comment by JamesHeinrich** [comment]
I hope this works for you, let me know if it does not.
https://github.com/JamesHeinrich/getID3/commit/1fad0f7a98904edb5df7a6a3dca077eff5d62fe8

**Comment by kgroeneveld** [comment]
Thank you for looking into this further. I tested your recent change and it does now report `cbr` vs `vbr` correctly for every file I tried. 

A couple small things I did notice is that it does not report an exact standard bitrate for non LAME cbr files when there is an `Info` header and it can return things like `CBR129` for `encoder_options`.  This is not really a problem for my usage as I can just round the results myself.

**Comment by JamesHeinrich** [comment]
Your sample 128kbps file, for example, has a bitrate of 128332 in the header (possibly taking into account the header frame? I didn't investigate). I changed the `encoder_options` code to use `round` instead of `ceil` and it should look better in most cases now.
https://github.com/JamesHeinrich/getID3/commit/a1a90e914590673d18cd9c9a51b2769a5b8d4ae2

**Comment by kgroeneveld** [comment]
>possibly taking into account the header frame? I didn't investigate 

I was curious about this and did some calculations even before your most recent post.

As you state the bitrate of the sample 128kbps file is reported as 128332. `VBR_bytes=160913` and `VBR_frames=384`, so:
`bitrate = 160913 / 384 * 44100 / 144 = 128332.30794270833333333333333333`

If you subtract out 417 byte of the `Info` frame you get:
`bitrate = (160913 - 417) / 384 * 44100 / 144 = 127999.73958333333333333333333333`

Which is as close as you can get to 128000 with the non integer ideal frame size.

I also encoded a 48000 sample rate file with ffmpeg which had `VBR_bytes=160896` and `VBR_frames=418`. getID3 reports:
`bitrate = 160896 / 418 * 48000 / 144 = 128306.22009569377990430622009569`

If you subtract out the bytes for the `Info` frame you get exactly:
`bitrate = (160896 - 384)  / 418 * 48000 / 144 = 128000`

I also tried encoding similar files with LAME with similar results.

It does seem quite odd that `VBR_frames` does not include the `Info` frame but `VBR_bytes` does. I don’t know if there is actually a good spec on this. Just because ffmpeg and LAME both do it this way doesn’t mean it is correct.

The test files I used for the above were only 10s long.  Most files would be longer and would have a smaller error as the size of the one extra frame becomes less significant. And I guess the opposite is also true, a _very_ short file could result in the bitrate calculation being way off.

One thing I did notice when I tested the LAME file is that getID3 reports an integer value for the bitrate, unlike the ones encoded by ffmpeg.  The code path triggered by LAME includes a call to `self::ClosestStandardMP3Bitrate`.
