### ISSUE TITLE
Division by zero on a mp3 file

### ISSUE THREAD

**Issue by paulijar** [JamesHeinrich/getID3#352]
Here's another case where an end user reported about crash during scanning while in my test environment analyzing the same file just logged a warning. The sample file will again follow shortly, and the relevant part of the stack trace is below.
```
DivisionByZeroError: Division by zero in /usr/local/nextcloud/apps/music/3rdparty/getID3/getid3/module.audio.mpc.php:404
Stack trace:
#0 /usr/local/nextcloud/apps/music/3rdparty/getID3/getid3/module.audio.mpc.php(54): getid3_mpc->ParseMPCsv6()
#1 /usr/local/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php(778): getid3_mpc->Analyze()
#2 /usr/local/nextcloud/apps/music/lib/Utility/ExtractorGetID3.php(75): getID3->analyze('/erwan/files/Mu...', 7086915, '', Resource id #1384)
```

PS. It's interesting how these reports about scanning issues get clustered: There has been months without a single report like this, and now I got two reports from two distinct users and about two distinct bugs within one hour (it just took a bit more time to get the sample file for this second case which is why I didn't report this already yesterday).

**Comment by JamesHeinrich** [comment]
Thanks for the sample file. getID3 was actually incorrectly detecting it as Musepack instead of MP3 (it looks like some bad ID3v2 tagger overwrote the beginning of the MP3 file when tagging the file). This revealed an overly-broad format check for Musepack that just happened to match the right 3 bytes in the head-truncated MP3 file.

Fixed in https://github.com/JamesHeinrich/getID3/commit/16afffd37def26c4d3e6cdbdbbbe606387dcf89f

**Comment by paulijar** [comment]
Thanks again for your quick actions! Seems to work fine now, as I no longer see those warnings.
