### ISSUE TITLE
GetID3 $tagWriter->WriteTags() returns false

### ISSUE THREAD

**Issue by Isaac-Amponsah** [JamesHeinrich/getID3#361]
I'm trying to change the metadata of an audio file using PHP library getID3 but $tagWriter->WriteTags() keeps returning false and I don't know what the problem is, here is my code:

    $track = "$root/src/tracks/$uploadedTrack";
    if (file_exists($track) ) {

      $cover_art_src = ($uploadedImg != null) ? 
        "$root/src/img/c-art/$uploadedImg" : "$root/src/img/macho-art.png";

      $imgMime = image_type_to_mime_type(exif_imagetype($cover_art_src));
      $tagAlbum = ($album != null) ? $album : "macho.com";
      require_once "/getid3/getid3.php";
      require_once "/getid3/write.php";

      $getID3 = new getid3;
      $tagWriter = new getid3_writetags;

      $textEncoding = 'UTF-8';
      $getID3->setOption(array('encoding'=>$textEncoding)); 

      $tagWriter->filename = $track;
      $tagWriter->tagformats = array('id3v2.3');
      $tagWriter->remove_other_tags = true;
      $tagWriter->overwrite_tags = true;
      $tagWriter->tag_encoding = $textEncoding;

      $TagData = array(
        'title'               => array($song_title),
        'artist'              => array($artist_name),
        'featuring'           => array($feature_name),
        'album'               => array($tagAlbum),
        'year'                => array($year),
        'genre'               => array($genre),
        'producer'            => array("produced by $producer"),
      );
      $TagData['attached_picture'][0]['data']          = file_get_contents($cover_art_src);
      $TagData['attached_picture'][0]['picturetypeid'] = 2; 
      $TagData['attached_picture'][0]['description']   = $song_title;
      $TagData['attached_picture'][0]['mime']          = $imgMime;

      $tagWriter->tag_data = $TagData;

      $res = $tagWriter->WriteTags());
      var_dump($res);
    }
Please can anyone help or point me to where the error is coming from.

**Comment by JamesHeinrich** [comment]
You have an extra trailing `)` on the WriteTags line in your code sample.
You may want to use `exif_imagetype` instead of hardcoding the picturetypeid.
Otherwise I ran your code sample (pointed to valid local test mp3 and jpg files) and it returned true and tagged the file with artist/title/etc and cover art.

You should examine `$tagWriter->warnings` and/or `$tagWriter->erorrs` if WriteTags fails.

**Comment by Isaac-Amponsah** [comment]
Thanks for the corrections but I'm getting this error message ``Tag format "id3v2.3" is not allowed on "" files``

**Comment by JamesHeinrich** [comment]
Prior to writing, getID3 will [check the existing file format](https://github.com/JamesHeinrich/getID3/blob/master/getid3/write.php#L167-L229) to make sure that the tag you specified is allowed to be written to that kind of file. It sounds like that check is failing to identify the file format of the existing file. My best guess is that you have an MP3 file with corruption at the beginning (e.g. usually caused by a badly written ID3v2 tag clobbering some of the beginning of the audio data) which is not uncommon. When a filename ends in ".mp3" getID3 will perform file-scanning checks to see if there is a mp3 data hiding further in the file, but presumably your  uploaded files are randomly named. There is a filename override parameter in `analyze` for reading, but no equivalent in the writing functions. You could test if renaming your uploaded file to end in ".mp3" solves the issue to confirm this is where the problem lies. Alternately you could temporarily hardcode something like "filename.mp3" as the 3rd parameter to `analyze` where it's called (currently [line 179 of write.php](https://github.com/JamesHeinrich/getID3/blob/master/getid3/write.php#L179)).

**Comment by Isaac-Amponsah** [comment]
Thank you for your time and clarification the error was not in this script it was in statement before this, thank you.
