### ISSUE TITLE
Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by QuixThe2nd** [JamesHeinrich/getID3#365]
Im getting the following error:
`Trying to access array offset on value of type int`
on line 29 of `getID3/getid3.lib.php`

PHP Version: 8

**Comment by StudioMaX** [comment]
A warning in this place can occur in many cases, most likely there is something wrong with the analyzed files.
Please attach a link to the problem file here, or send it to info@getid3.org

**Comment by QuixThe2nd** [comment]
Here's the file: https://ugc.starfiles.co/file/H4KAmR590i6y/ARMCPUZ1-5-1Dangerou

**Comment by JamesHeinrich** [comment]
The provided sample seems to be a normal zip file structure. I did not encounter any errors or warnings on PHP v8.0.11 or v7.4.1

**Comment by QuixThe2nd** [comment]
Im getting it on PHP 8.0.14

**Comment by StudioMaX** [comment]
Looks like this warning going from that condition
https://github.com/JamesHeinrich/getID3/blob/73a25a84ae111a59c2bb8703217aa971ab6fd997/getid3/module.archive.zip.php#L298-L303

`$LocalFileHeader['data_descriptor']['signature']` in this case is `(int) 3528876101/ 0xD2566045` instead of expected `0x08074B50`. Therefore, the signature is passed as an integer to PrintHexBytes, which expects a string.

**Comment by JamesHeinrich** [comment]
This slightly inelegant change should fix it I think?
https://github.com/JamesHeinrich/getID3/commit/e1e92b163b61f37b56a32006a7f6af9e83bb6b78
