### ISSUE TITLE
wrong encoding windows-1251

### ISSUE THREAD

**Issue by vitaha85** [JamesHeinrich/getID3#51]
Hi
I have wrong encoding windows-1251
My code:
...
$getid3 = new getID3;
$getid3->encoding = 'UTF-8';
$fileinfo = $getid3->Analyze(Yii::getPathOfAlias('webroot').$file);
....
if( !empty($fileinfo['tags']['id3v1']['title']) ){
    $audio->name = $fileinfo['tags']['id3v1']['title'][0];
}
...

fileinfo['tags']['id3v1']['title'][0] return  string - "Ãîëàÿ" , but the correct result 'Голая'

I did that small fix in file getid3.lib.php:

...
public static function detect_encoding($string) {
        static $list = array('ASCII', 'utf-8', 'windows-1251');
        foreach ($list as $item) {
            if (strcmp(@iconv($item, $item, $string), $string) == 0)
                return $item;
        }
        return null;
}

public static function iconv_fallback($in_charset, $out_charset, $string) {

        if ($in_charset == $out_charset) {
            return $string;
        }

       // windows-1251 encoding
        if(self::detect_encoding($string) == 'windows-1251') {
            $converted_string = mb_convert_encoding($string, "utf-8", "windows-1251");
            return $converted_string;
        }

        // iconv() availble
        if (function_exists('iconv')) {
		if ($converted_string = @iconv($in_charset, $out_charset.'//TRANSLIT', $string)) {
			switch ($out_charset) {
				case 'ISO-8859-1':
					$converted_string = rtrim($converted_string, "\x00");
					break;
			}
			return $converted_string;
		}

		// iconv() may sometimes fail with "illegal character in input string" error message
		// and return an empty string, but returning the unconverted string is more useful
		return $string;
    }
   ....

}

**Comment by JamesHeinrich** [comment]
I have considered your code, but rather than put it in the general-purpose iconv_fallback function I have put it inside getid3.php HandleAllTags()

My new code block will check only for ID3v1 tags, and if the tag data consists entirely of upper-range (128-255) byte values then it will check for Windows-1251 or KOI8-R with a method similar to your above code. If non-standard encoding is detected, the detected encoding is used for the conversion of the raw ID3v1 data to the encoded version returned in ['tags'] (and ['comments']), which is where you should be accessing tag data values from.

https://github.com/JamesHeinrich/getID3/commit/63026be3dbed210596c572509c5636dc90a4db60

**Comment by vitaha85** [comment]
Thanks
Good job, good luck!
