### ISSUE TITLE
Wrong FPS for QuictTime (mov) files

### ISSUE THREAD

**Issue by TomaszKane** [JamesHeinrich/getID3#54]
Hi,
I download Tears of Steel in 720p .mov from https://mango.blender.org/download/ and `$fileInfo['video']['frame_rate']` says it has 1000 fps.

I believe it's wrong.

**Comment by artur-ciesielski** [comment]
I think I can help pinpoint the issue a bit better.

In line 167 the frame rate for the video is being set if it has not been set/read before. But for the Tears of Steel .mov file the frame rate is already set to 1000 after a call to QuicktimeParseAtom in line 140 while parsing the 'moov' atom.

Also tested it on other files and there is no such issue.

**Comment by JamesHeinrich** [comment]
QuickTime is sometimes annoying to work with due to the possibility of variable framerates, and framerate values (like most other things QuickTime) are store in multiple places.

I have made a change that should fix this particular problem, perhaps other similar problems, but there's also a small chance it may have broken some previously-working files. Please let me know if that is the case.
https://github.com/JamesHeinrich/getID3/commit/bdf0739fee0564b5caa816004dddc158203b4f02
