### ISSUE TITLE
Cyrillics detect fix

### ISSUE THREAD

**Issue by u07** [JamesHeinrich/getID3#80]
Hello, guys! I'm from russian-speaking country and I must notice, that the "ID3v1 encoding detection hack" in the getid3.php line 1246 does not work.

This code looks through all the tags, looking for one which contains only cyrillics:

` if (preg_match('#^[\\x80-\\xFF]+$#', $value)) `

But no one of them match because of..... spaces :-)  Cause 0x80...0xFF covers only the alphabet and does not cover special chars, see: http://vk.cc/5ua21p   

So, if we rewrite it like this   ` '#^[\\x00-\\x40\\xA8\\B8\\x80-\\xFF]+$#' `  we'll make the world better. 

![beforeafter](https://cloud.githubusercontent.com/assets/20968145/17642105/8ab5a372-615b-11e6-8b09-d50a85183a41.png)

Actually I can't say it will fix 100% tracks, cause it's not uncommon to name a group or track with latin includings. Like The Very Best Of (cyrillic_artist_name), or foreign artist with only the song name translated, or special remarks like "Luciano Pavarotti - Вернись в Сорренто (remastered)". And so on.

Test .mp3 set: https://yadi.sk/d/1DZiwg8ru8h4M

**Comment by JamesHeinrich** [comment]
I made some fixes (including your suggestion) in https://github.com/JamesHeinrich/getID3/commit/7c7eb57be2adc90b28e167c124c368f1d04b0460

But don't expect perfection if the input file is broken. For example, using your sample file the ID3v1 displays (mostly) correctly now, but the ID3v2 is broken because the tags are written in CP1251 but the tag is encoded as ISO-8859-1, which is wrong. You should retag your files with a multi-byte-encoding aware tagger (which should be pretty much anything) so that the ID3v2 tag is written as UTF-8 (or UTF-16 if you prefer).

**Comment by u07** [comment]
Thanks for the fixes. But you know, there are tons of music encoded this way, I saw enough examples. What do you think, may be it's safe to expand this hack to id3-v2 tags as well? Cause using cp1251 in id3-v1 is kind of a violation too..

**Comment by JamesHeinrich** [comment]
No, it will not be expanded to ID3v2.
ID3v1 doesn't have any mechanism for specifying character sets, and there was no alternative before ID3v2 was introduced, so the spec violation is unfortunate but understandable.
There is no excuse for using the wrong encoding in ID3v2.

**Comment by u07** [comment]
I see, but usually users don't care about such matters (they just have their mp3s and want them ok) and I suppose we'll never find (and punch) people who produce such kind of id3-v2 tags... May be some switch then? Let's say... if (id3v1==true or crazyRussians==true) {check_1251}

**Comment by JamesHeinrich** [comment]
I'll leave that to the getID3 user if they want to second-guess the specified tag encoding and juggle things around with iconv or mb_convert_encoding.

**Comment by u07** [comment]
Ok, one more question. Did you try the new version with that 3 test tracks? How many correct do you have? My friend says that with new version of getid3.php his project now does not recognize cyrillics. There was 1 track of 3 recognized before and 0/3 after. That's a bit strange, cause an old version plus new regexp shows 3/3...

**Comment by JamesHeinrich** [comment]
ID3v1 is automatically interpreted as Windows-1251
ID3v2 treated as ISO-8859-1 because that's the encoding the ID3v2 tag claims to be in.
The [comments] key will generally be returned with ID3v2 data overriding equivalent ID3v1 data.
If you have a lot of these broken files with CP1251 encoding you may want to access [tags][id3v1] instead of [comments].
![](http://i.imgur.com/ixzDx87.png)

**Comment by u07** [comment]
Yeah, I guessed that may be id v2 overriding... It's clear now, thanks.
