### ISSUE TITLE
Updated file gives the same FileInfo.

### ISSUE THREAD

**Issue by bilalba** [JamesHeinrich/getID3#81]
I'm using the getID3 library to get the details of a remote video file. I'm trying to read a portion of the file to get the details of the file.

For these videos, I'm trying to download the full video, and then extract the relevant information. However, even after the video has downloaded completely, getID3->analyze($filename), returns the same erroneous file info.

But when I copy the video, and then run the function analyze($filename.'copied.mp4') on copied video, it returns the correct info even though the file contents are same. Perhaps getID3 isn't loading the video again, however, how can I fix this issue without copying the video.

Please find the code below.

```
if ($fp_remote = fopen($remotefilename, 'r')) {
    echo 'conn opened'; 
    $localtempfilename = tempnam('/home/xerox/abc', 'whateva').'.mp4';
    if ($fp_local = fopen($localtempfilename, 'wb')) {
        $count = 0;
        $countExpiry = 8;
        while ($buffer = fread($fp_remote, 8192)) {
            $count++;
            fwrite($fp_local, $buffer);
            if ($count >= $countExpiry) {
                fflush($fp_local);
                $getID3 = new getID3;
                $ThisFileInfo = $getID3->analyze($localtempfilename);
                if ($ThisFileInfo["error"]){
                    print "problem encouterd";
                    $countExpiry += 1000;
                } else {
                 break;}
            }
        }
        fclose($fp_local);
        $getID31 = new getID3;
        copy ( $localtempfilename, $localtempfilename.'_copied.mp4' );
        $ThisFileInfoz = $getID31->analyze($localtempfilename.'_copied.mp4');
        // Delete temporary file
        unlink($localtempfilename);
        fclose($fp_remote);
    var_dump($ThisFileInfoz);
    }

}
```

**Comment by JamesHeinrich** [comment]
Sorry, I'm not quite sure I follow your question. Since getID3 doesn't operate on remote files it's left to the user to implement any remote file copying, which it looks like you've done. It looks like you're copying 8kB at a time and analyzing the file repeatedly until you don't get an error? I haven't experimented with using getID3 like that (multiple times repeatedly on a changing file). Perhaps(?) a call to [clearstatcache](http://www.php.net/manual/en/function.clearstatcache.php) before analysis (after your [fflush](http://www.php.net/manual/en/function.fflush.php) call would be good) may solve your problem, since repeated calls to things like [filesize](http://www.php.net/manual/en/function.filesize.php) will be cached by the filesystem and getID3 won't read beyond end-of-file.

**Comment by bilalba** [comment]
A call to clearstatcache solved the problem! Thank you!
