### ISSUE TITLE
Memory limit issue in getid3.php

### ISSUE THREAD

**Issue by Austinb** [JamesHeinrich/getID3#88]
I ran an update to pull down the latest dev-master and notice a new issue with memory limits.  It appears the change on July 25, 2016 in commit 0e6c1a3 is causing the library to go over the PHP's defined memory limit if the file being read is larger than the memory limit. I rolled back to **_stable_** which is 1.9.12 from March 2, 2016 and the issue went away. 

Error excerpt trying to read information about a 420MB mp4 video file in PHP 5.5.38 with a memory limit defined as 256MB in the php.ini. Centos 6.8 Final updated as of this morning. 

```php 
'Allowed memory size of 268435456 bytes exhausted (tried to allocate 134217729 bytes)' in ./vendor/james-heinrich/getid3/getid3/getid3.php:1707
```

Which is part of this chunk which was changed in 0e6c1a3:
```php
                //return fread($this->getid3->fp, $bytes);
		/*
		* http://www.getid3.org/phpBB3/viewtopic.php?t=1930
		* "I found out that the root cause for the problem was how getID3 uses the PHP system function fread().
		* It seems to assume that fread() would always return as many bytes as were requested.
		* However, according the PHP manual (http://php.net/manual/en/function.fread.php), this is the case only with regular local files, but not e.g. with Linux pipes.
		* The call may return only part of the requested data and a new call is needed to get more."
		*/
		$contents = '';
		do {
			$part = fread($this->getid3->fp, $bytes);
			$partLength  = strlen($part);
			$bytes      -= $partLength;
			$contents   .= $part;
		} while (($bytes > 0) && ($partLength > 0));
		return $contents;
```

So it appears trying the read the file contents into a variable is not the best solution to the fread() length issue as it causes PHP to hit the memory limit.

**Comment by JamesHeinrich** [comment]
I don't believe the size of the file vs the size of your PHP memory are related.

At a quick look at the fread block I don't see any obvious problem.
How many $bytes are attempting to be read in your case where it runs into the memory limit?
I suppose potentially there could be an extra $bytes of memory used by reading into a variable and returning rather than returning directly from fread, but for that to be significant there must be an attempt to read a large chunk of file (10s or 100s of MB?)

**Comment by Austinb** [comment]
I ran more specific testing and found that many mp4 files I passed to it would cause the error regardless of the mp4's file size relative to the memory limit (256MB).  Every wmv and mov file I tried worked as expected regardless of their file size. If I uncomment line 1694 the mp4 files work as expected.   The test mp4 files I found online around 40MB all appeared to work but when I tried larger mp4 files from http://www.h264info.com/clips.html the same memory limit issue happens.  I tested the Gravity (364MB) and Simpson's movie (144MB) trailers and both hit the memory limit. 

So it appears to be something with mp4s when that code block was changed. I was able to step through and narrow down the issue to the call to while loop starting on line 39 in module.audio-video.quicktime.php.  At some point in that loop it maybe the $AtomHeader variable is getting too large or the call to QuicktimeParseAtom() but I am not sure.   Hopefully this helps narrow things down a bit. 

Let me know if you have something I can test to see if the issue is fixed.  Again the old straight fread() on line 1694 does not cause the memory limit issue for any of the mp4s that have issues with the fread() changes. 

Pulled latest dev from github:
```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing james-heinrich/getid3 (v1.9.12)
  - Installing james-heinrich/getid3 (dev-master 9abdfcb)
    Downloading: 100%
```

Testing code:
```php
// Initialize getID3 engine
$getID3 = new \getID3();
$getID3->setOption(['encoding' => 'UTF-8']);

// Analyze file and store returned data
$fileinfo = $getID3->analyze($filename);
```

**Comment by JamesHeinrich** [comment]
As luck would have it I came across a 700MB .mp4 today and threw it at getID3 which immediately choked as described.

(Fortunately it's an easy fix, in [module.audio-video.quicktime.php line 38](https://github.com/JamesHeinrich/getID3/blob/master/getid3/module.audio-video.quicktime.php#L38)
```
$atom_data_read_buffer_size = ($info['php_memory_limit'] ? round($info['php_memory_limit'] / 2) : $this->getid3->option_fread_buffer_size * 1024);
```
Note the readbuffer set to memory_limit / 2 -- so of course you read half into the temp variable and half into the target variable and have nothing left to run the code. The quick fix is to change "2" to something larger, like "4". Larger read buffers are generally faster, but that doesn't help if you run out of memory :)

Fixed in https://github.com/JamesHeinrich/getID3/commit/9b0d39d8769e1b24ca371f3e8dbbe3b27f5907f7
