### ISSUE TITLE
Multi-valued genre tags don't seem to work correctly for MP3.

### ISSUE THREAD

**Issue by dseomn** [JamesHeinrich/getID3#89]
Hi,

I have [some files](https://github.com/JamesHeinrich/getID3/files/629989/multiple-genre-test-files.zip) that are supposed to have equivalent tags, each with multiple genres. (The two genres are added/2016 and context/soundtrack.) The FLAC and OGG files seem to work right, but the genres in the MP3 file are not correct. I'm not sure if the error is in getID3 or in the programs I use to write tags, so apologies if this is the wrong place to file a bug. Here are the tags from getID3 (provided to me by somebody else):

```
440Hz.ogg
 comments.genre = "context/soundtrack"
 ogg.comments.genre.0 = "added/2016"
 ogg.comments.genre.1 = "context/soundtrack"
 tags.vorbiscomments.genre.0 = "added/2016"
 tags.vorbiscomments.genre.1 = "context/soundtrack"

440Hz.mp3
 comments.genre = "context/soundtrack"
 id3v2.TCON.0.data = "added/2016context/soundtrack"
 tags.id3v2.genre.0 = "added"
 tags.id3v2.genre.1 = "context"
 tags.id3v2.genre.2 = "soundtrack"
 id3v2.comments.genre.0 = "added"
 id3v2.comments.genre.1 = FALSE
 id3v2.comments.genre.2 = "context"
 id3v2.comments.genre.3 = "soundtrack"

440Hz.flac
 comments.genre = "context/soundtrack"
 flac.VORBIS_COMMENT.comments.genre.0 = "added/2016"
 flac.VORBIS_COMMENT.comments.genre.1 = "context/soundtrack"
 flac.comments.genre.0 = "added/2016"
 flac.comments.genre.1 = "context/soundtrack"
 tags.vorbiscomments.0 = "added/2016"
 tags.vorbiscomments.1 = "context/soundtrack" 
```

**Comment by JamesHeinrich** [comment]
Your tag-writer is working fine, the bug was in getID3.

Unfortunately there are a large number of programs that write ID3v2 tags, and a large number of those break the specs in one way or another. getID3 tries to work around the known issues as best it can, but in this case one of the workarounds broke your correctly-written tags.

I have rewritten (https://github.com/JamesHeinrich/getID3/commit/f4e51aabbd78eb52f08c0e0257b2d0f0b7c1463a) that part of the code to hopefully interfere less with correctly-written tags. Your test case shows up correctly now, thanks for the sample files.

**Comment by dseomn** [comment]
If I understand your change correctly, a file with a single genre of "foo/bar" would still be split into "foo" and "bar". Is that correct? I have many files like that. And for what it's worth, most of them are written by MusicBrainz Picard, so I'm not sure the comment is still accurate.

Here are some files written by Picard 1.3.2-3 with a single genre with a slash: [slash-genre-test-file.zip](https://github.com/JamesHeinrich/getID3/files/634276/slash-genre-test-file.zip)

**Comment by JamesHeinrich** [comment]
No, your "added/2016" stays intact as a single genre.

**Comment by dseomn** [comment]
Thanks!
